---
abstract: 'Refer to module/sub/spec/sub call via URI string'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-URI
requires:
  Test::More: 0.96
  URI: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-URI/
  repository: http://github.com/sharyanto/perl-Sub-Spec-URI
version: 0.03
